config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about"

  resources :books, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update,:create,:new] do
    resource :relationships, only: [:create, :destroy]
    get 'following' => 'relationships#following', as: 'following'
    get 'followeds' => 'relationships#followeds', as: 'followeds'
  end
  
  get "/search", to: "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!


  def create
    #user = User.find(params[:user_id])
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    #user = User.find(params[:user_id])
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def following
    user = User.find(params[:user_id])
    @users = user.following
  end

  def followeds
    user = User.find(params[:user_id])
    @users = user.followeds
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_btn.html.erb
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: options[:class].presence || "btn btn-info" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: options[:class].presence || "btn btn-success" %>
  <% end %>
<% end %>

app/views/relationships/followeds.html.erb
<h2>フォロワー数</h2>
<% if @users.exists? %>
  <%= render "/users/index", users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/following.html.erb
<h2>フォロー数</h2>
<% if @users.exists? %>
  <%= render "/users/index", users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>